# Generated by Django 5.1.1 on 2025-05-08 13:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Full Title', max_length=50)),
                ('shr_title', models.CharField(default='Short Title', max_length=20)),
                ('first_img', models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/up_images')),
                ('second_img', models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/up_images')),
                ('desc', models.CharField(default='Description', max_length=255)),
                ('price', models.IntegerField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Admin', max_length=20)),
                ('title', models.CharField(default='Write a Title', max_length=50)),
                ('desc', models.CharField(default='description', max_length=70)),
                ('main_img', models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/up_images')),
                ('img1', models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/up_images')),
                ('img2', models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/up_images')),
                ('img3', models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/up_images')),
                ('category1', models.CharField(blank=True, choices=[('agro tourism', 'Agro Tourism'), ('adventure', 'Adventure'), ('amusement', 'Amusement'), ('boating', 'Boating'), ('waterfall', 'Waterfall'), ('water park', 'Water Park'), ('tech', 'Tech'), ('ai', 'Ai')], max_length=20, null=True)),
                ('category2', models.CharField(blank=True, choices=[('agro tourism', 'Agro Tourism'), ('adventure', 'adventure'), ('amusement', 'amusement'), ('boating', 'boating'), ('waterfall', 'waterfall'), ('water park', 'water park'), ('tech', 'Tech'), ('ai', 'AI')], max_length=20, null=True)),
                ('category3', models.CharField(blank=True, choices=[('agro tourism', 'Agro Tourism'), ('adventure', 'adventure'), ('amusement', 'amusement'), ('boating', 'boating'), ('waterfall', 'waterfall'), ('water park', 'water park'), ('tech', 'Tech'), ('ai', 'AI')], max_length=20, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('date_created', models.DateTimeField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
