# Generated by Django 5.1.1 on 2025-05-10 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0002_contact_packages_rename_deals_special_packages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category2',
            field=models.CharField(blank=True, choices=[('agro tourism', 'Agro Tourism'), ('adventure', 'Adventure'), ('amusement', 'Amusement'), ('boating', 'Boating'), ('waterfall', 'Waterfall'), ('water park', 'Water park'), ('tech', 'Tech'), ('ai', 'AI')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category3',
            field=models.CharField(blank=True, choices=[('agro tourism', 'Agro Tourism'), ('adventure', 'Adventure'), ('amusement', 'Amusement'), ('boating', 'Boating'), ('waterfall', 'Waterfall'), ('water park', 'Water park'), ('tech', 'Tech'), ('ai', 'AI')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.CharField(blank=True, choices=[('water park', 'Water Park'), ('adhishakti water park', 'Adhishakti Water Park'), ('agro tourism', 'Agro Tourism'), ('boating', 'Boating')], max_length=70, null=True)),
                ('phone', models.IntegerField()),
                ('number', models.IntegerField()),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
