# Generated by Django 5.1.1 on 2025-05-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0003_alter_post_category2_alter_post_category3_enquire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
