# Generated by Django 5.1.1 on 2025-05-10 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0005_remove_enquire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
