# Generated by Django 5.1.1 on 2025-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0006_alter_enquire_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
