# Generated by Django 5.1.1 on 2025-05-12 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0007_alter_enquire_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
