# Generated by Django 5.1.1 on 2025-05-13 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0009_enquire_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
