# Generated by Django 5.1.1 on 2025-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0010_packages_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='img',
            field=models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/up_images'),
        ),
    ]
