# Generated by Django 5.1.1 on 2025-05-13 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0011_packages_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dis_img', models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/gallery')),
                ('img', models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/gallery')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
