# Generated by Django 5.1.1 on 2025-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0012_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='dis_img',
            field=models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/up_images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='image/up_images'),
        ),
    ]
