# Generated by Django 5.1.1 on 2025-05-16 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivtirth_app', '0013_alter_gallery_dis_img_alter_gallery_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='dis_img',
            field=models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='cloud_folder/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='cloud_folder/'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='img',
            field=models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='cloud_folder/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='cloud_folder/'),
        ),
        migrations.AlterField(
            model_name='special_packages',
            name='first_img',
            field=models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='cloud_folder/'),
        ),
        migrations.AlterField(
            model_name='special_packages',
            name='second_img',
            field=models.ImageField(blank=True, default='image/new/31150.jpg', null=True, upload_to='cloud_folder/'),
        ),
    ]
